Sprint 04
EvgeniyKostyaev/MovieQuiz pull request #1
Opened 2024-12-05 15:11 UTC by EvgeniyKostyaev

2024-12-05 17:41 UTC, Kirchberg requested changes
⚠️ Критические замечания (это нужно исправить обязательно):

1. Шрифт кнопок не соответствует макету, необходимо поправить в соответствии с пунктом задания 3. [См. скриншот сравнения симулятора и макета](https://ibb.co/NSGtjhk)

Без исправлений этих пунктов, я не смогу принять у тебя работу. Если возникнут вопросы, обязательно задавай их Наставнику!

2024-12-05 17:41 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
У меня есть предложение по его улучшению, которое может сделать его более компактным и читаемым.

Когда нужно инициализировать несколько объектов одного типа и добавить их в массив, можно создать массив этих объектов напрямую, без необходимости инициализировать каждую переменную отдельно и добавлять её в массив. Это сделает код более лаконичным и простым для восприятия.

Вот как можно было бы переписать твой метод:
```swift
private func createQuizQuestions() -> [QuizQuestion] {
    let quizQuestions: [QuizQuestion] = [
        QuizQuestion(image: "The Godfather", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
        QuizQuestion(image: "The Dark Knight", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
        QuizQuestion(image: "Kill Bill", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
        QuizQuestion(image: "The Avengers", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
        QuizQuestion(image: "Deadpool", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
        QuizQuestion(image: "The Green Knight", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
        QuizQuestion(image: "Old", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: false),
        QuizQuestion(image: "The Ice Age Adventures of Buck Wild", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: false),
        QuizQuestion(image: "Tesla", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: false),
        QuizQuestion(image: "Vivarium", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: false)
    ]

    return quizQuestions
}
```

2024-12-05 17:41 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
Было бы хорошо поправить отступы таким образом, так чтение кода облегчается, а также упрощается добавление нового параметра за счет того, что не нуэно переносить скобку в конце.
```swift
let quizStepViewModel = QuizStepViewModel(
    image: UIImage(named: model.image) ?? UIImage(),
    question: model.text,
    questionNumber: "\(currentQuestionIndex + 1)/\(questions.count)"
)
```

2024-12-05 17:41 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    // MARK: - Action methods
До и после MARK обычно оставляют одну пустую строку кода, это облегчает нахождение самого MARK, а также явно отделяет разные секции кода

2024-12-07 08:49 UTC, Kirchberg approved these changes
Обращу внимание, что пользователь может случайно прожать два раза кнопку ответа или даже много и быстро понажимать на кнопки. 
Это может привести к неверному увеличению счетчика, или лишнего вызова алерта с результатом. Принято такое поведение блокировать на время выполнения операции запроса следующего вопроса.

Можно использовать свойство [isEnabled](https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled). 
До начала смены вопроса "выключать" кнопку, после отображения свежих данных "включать"

Не забудь вмерджить пул-реквест в основную ветку.
Успехов в следующем задании!

2024-12-09 07:12 UTC, EvgeniyKostyaev commented
Кирил, просто для информации, я реализовал enable/disable  action buttons в этом коммите  https://github.com/EvgeniyKostyaev/MovieQuiz/pull/1/commits/5c5d3a77450f272fa40fbd5ff07036e00ea6a718

2024-12-09 07:14 UTC, EvgeniyKostyaev commented
> Обращу внимание, что пользователь может случайно прожать два раза кнопку ответа или даже много и быстро понажимать на кнопки. Это может привести к неверному увеличению счетчика, или лишнего вызова алерта с результатом. Принято такое поведение блокировать на время выполнения операции запроса следующего вопроса.
> 
> Можно использовать свойство [isEnabled](https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled). До начала смены вопроса "выключать" кнопку, после отображения свежих данных "включать"
> 
> Не забудь вмерджить пул-реквест в основную ветку. Успехов в следующем задании!

Кирил, спасибо за ревью! Просто для информации, я реализовал enable/disable action buttons в этом коммите https://github.com/EvgeniyKostyaev/MovieQuiz/commit/5c5d3a77450f272fa40fbd5ff07036e00ea6a718

2024-12-09 07:16 UTC, merged